### ISSUE TITLE
Can't make it work with only one element

### ISSUE THREAD

**Issue by sconxu** [machadogj/react-native-carousel-control#11]

**Comment by machadogj** [comment]
Hi @sconxu, do you see any error messages? What do you see?

**Comment by sconxu** [comment]
Hi. This is the error i get: 

![simulator screen shot sep 8 2016 7 52 45 pm](https://cloud.githubusercontent.com/assets/3735664/18358514/13ae0b7c-75fe-11e6-94b6-ce26d2d06980.png)

**Comment by machadogj** [comment]
Can you show me the code?

**Comment by sconxu** [comment]
Sure, 

`<Carousel
                    pageStyle={{backgroundColor: 'white', borderRadius: 5}}
                    pageWidth={Config.productsCarouselPageWidth}
                    sneak={75}
                    initialPage={0}
                >`
                    `<CarouselElement content={carouselElementContent}/>`
`</Carousel`>

**Comment by machadogj** [comment]
Can you try changing `<CarouselElement>` with `<Text>Hello world</Text>`?
If that works, then CarouselElement's render might be returning "null" (??).

**Comment by machadogj** [comment]
Actually, sorry, my bad, looks like it's not an array when there's only one
element:
https://facebook.github.io/react/tips/children-props-type.html
I'll try to fix this later today. Feel free to submit a PR if you want.
Thanks for reporting!

**Comment by sconxu** [comment]
Yep. Sounds like it. Thanks for the quick response!

**Comment by machadogj** [comment]
@sconxu this has been fixed by @csettle-sl and published in v1.0.4. Thanks!
