### ISSUE TITLE
 Is it possible to know the carousel index card inside the card?

### ISSUE THREAD

**Issue by FilipMessa** [machadogj/react-native-carousel-control#19]
I'm trying to resize the cards when active, but i don'k now how know the card if is active.
Is there some way to achieve this?

thanx

**Comment by waleedarshad-vf** [comment]
+1

**Comment by machadogj** [comment]
Hi @FilipMessa, will the "onPageChange" not work for you? Gives you the index of the active card.

**Comment by waleedarshad-vf** [comment]
@FilipMessa yes it works. sorry i just followed it blindly. it is working absolutely fine.  actually document should be update that "onPageChange will return index of selected page" :)

Thanks

**Comment by machadogj** [comment]
@waleedarshad-vf I agree that docs should be updated! Thanks.
@FilipMessa let me know if this is ok for you!

**Comment by FilipMessa** [comment]
@machadogj Yes it is ok thanks
