### ISSUE TITLE
super expression must be either null

### ISSUE THREAD

**Issue by greenteamer** [machadogj/react-native-carousel-control#5]
Hello!

Thank you for your module, can you tell me, why i getting this error 
"Uncaught TypeError: Super expression must either be null or a function, not undefined"

If i import your Component from 'react' instead of 'react-native' - I getting 

undefined is not an object 
on 143 line 

143:  { pages } 

Thank you!

**Comment by ssancheza227** [comment]
Hello, I have the same problem, this says: "Super expression must either be null or a function, not undefined". 

Thank.

---

I fix this temporarily with an ListView in mode horizontal=true :)

**Comment by machadogj** [comment]
Thanks for reporting this! This had to do with the syntax for import in react native ^0.26. I have added a fix for this on `3e8941b`, npm version 1.0.2.
