### ISSUE TITLE
initialPage props is not working

### ISSUE THREAD

**Issue by karthickvkumar** [machadogj/react-native-carousel-control#6]
Hi @machadogj thanks for this awesome library, When i tried passing initalPage props in carousle. Its not working in android. Its just simply taking the default props
`<Carousel initialPage={3}>
....
</Carousel>`

It would be helpful if u provide any solution for this

Thanks in Advance

**Comment by machadogj** [comment]
Hi, thanks for reporting, I have fixed this in `3e8941b` npm version 1.0.2.

**Comment by sergioribeiro** [comment]
How do I fix it? I'm using a newer version and having the same problem.

npm -v react-native-carousel-control
2.15.8

**Comment by machadogj** [comment]
Hi @sergioribeiro, try with `npm install react-native-carousel-control@latest`.

**Comment by sergioribeiro** [comment]
Thanks for the prompt response @machadogj. 
Just updated and it is still taking the default one "0". :(
